# Using megagroups. ..ansible/inventories/prd/hosts.yml  

# MetaGroups - Grouping groups together. (MAIN)
all:
  children:
    site_a:
      children:
        site_a_web:
        site_a_db:
    site_b:
      children:
        site_b_web:
        site_b_db:
    site_x:
      children:
        site_x_ansible:

# MetaGroups - Secondary : All Web Servers : EXTRA GROUPING - Both Sites ==
all_web:
  children:
    site_a_web:
    site_b_web:

# =================================================================================================================== # 


# == Site A (22)==
site_a_web:
  hosts:
    web1.sitea.local:
      ansible_host: 192.22.50.2
    web2.sitea.local:
      ansible_host: 192.22.50.3

site_a_db:
  hosts:
    db1.sitea.local:
      ansible_host: 192.22.51.2


# == Site B (33)==
site_b_web:
  hosts:
    web1.siteb.local:
      ansible_host: 192.33.50.2
    web2.siteb.local:
      ansible_host: 192.33.50.3

site_b_db:
  hosts:
    db1.siteb.local:
      ansible_host: 192.33.51.2


# == Site X (11)==
site_x_ansible:
  hosts:
    ansible.sitex.local:
      ansible_host: 192.168.50.166



# == Below is the old way of doing it without megagroups. ==
# all:
#   children:
#     site_a:
#       children:
#         site_a_web:
#         site_a_db:
#     site_b:
#       children:
#         site_b_web:
#         site_b_db:
#     site_x:
#       children:
#         site_x_ansible:
#           hosts:
#             ansible.sitex.local: 
#               ansible_host: 192.168.50.166 